// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.6.1
// source: output.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OutputMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HuqName       string                 `protobuf:"bytes,1,opt,name=huq_name,json=huqName,proto3" json:"huq_name,omitempty"`
	HuqVersion    string                 `protobuf:"bytes,2,opt,name=huq_version,json=huqVersion,proto3" json:"huq_version,omitempty"`
	InvocationId  string                 `protobuf:"bytes,3,opt,name=invocation_id,json=invocationId,proto3" json:"invocation_id,omitempty"`
	Source        string                 `protobuf:"bytes,4,opt,name=source,proto3" json:"source,omitempty"`
	Line          string                 `protobuf:"bytes,5,opt,name=line,proto3" json:"line,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OutputMessage) Reset() {
	*x = OutputMessage{}
	mi := &file_output_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OutputMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OutputMessage) ProtoMessage() {}

func (x *OutputMessage) ProtoReflect() protoreflect.Message {
	mi := &file_output_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OutputMessage.ProtoReflect.Descriptor instead.
func (*OutputMessage) Descriptor() ([]byte, []int) {
	return file_output_proto_rawDescGZIP(), []int{0}
}

func (x *OutputMessage) GetHuqName() string {
	if x != nil {
		return x.HuqName
	}
	return ""
}

func (x *OutputMessage) GetHuqVersion() string {
	if x != nil {
		return x.HuqVersion
	}
	return ""
}

func (x *OutputMessage) GetInvocationId() string {
	if x != nil {
		return x.InvocationId
	}
	return ""
}

func (x *OutputMessage) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *OutputMessage) GetLine() string {
	if x != nil {
		return x.Line
	}
	return ""
}

var File_output_proto protoreflect.FileDescriptor

const file_output_proto_rawDesc = "" +
	"\n" +
	"\foutput.proto\x12\x05proto\"\x9c\x01\n" +
	"\rOutputMessage\x12\x19\n" +
	"\bhuq_name\x18\x01 \x01(\tR\ahuqName\x12\x1f\n" +
	"\vhuq_version\x18\x02 \x01(\tR\n" +
	"huqVersion\x12#\n" +
	"\rinvocation_id\x18\x03 \x01(\tR\finvocationId\x12\x16\n" +
	"\x06source\x18\x04 \x01(\tR\x06source\x12\x12\n" +
	"\x04line\x18\x05 \x01(\tR\x04lineB\x03Z\x01.b\x06proto3"

var (
	file_output_proto_rawDescOnce sync.Once
	file_output_proto_rawDescData []byte
)

func file_output_proto_rawDescGZIP() []byte {
	file_output_proto_rawDescOnce.Do(func() {
		file_output_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_output_proto_rawDesc), len(file_output_proto_rawDesc)))
	})
	return file_output_proto_rawDescData
}

var file_output_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_output_proto_goTypes = []any{
	(*OutputMessage)(nil), // 0: proto.OutputMessage
}
var file_output_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_output_proto_init() }
func file_output_proto_init() {
	if File_output_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_output_proto_rawDesc), len(file_output_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_output_proto_goTypes,
		DependencyIndexes: file_output_proto_depIdxs,
		MessageInfos:      file_output_proto_msgTypes,
	}.Build()
	File_output_proto = out.File
	file_output_proto_goTypes = nil
	file_output_proto_depIdxs = nil
}
